"""
URL configuration for web_project project.

GENERATED BY: django-admin startproject (Django 4.2.27)
Original Source: https://docs.djangoproject.com/en/4.2/topics/http/urls/

This file was generated by Django's startproject command and then customized
with app-specific URL configurations.
"""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path


urlpatterns = [
    path("", include("appCore.urls")),
    path('admin/', admin.site.urls)
]

urlpatterns += staticfiles_urlpatterns() 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

